import Link from 'next/link'
import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
      //  className={inter.className}
       >
        <header>
          <nav className='nav'>
            <div className='logo'>
              <Link href='/'>
                <img src='../images/logo.png'/>
              </Link>
            </div>
            <div>
              <ul>
                <li>
                  <Link href='/list'>글목록</Link>
                </li>
                <li>
                  <Link href='/write'>글쓰기</Link>
                </li>
              </ul>
            </div>
          </nav>
        </header>


        
        {children}</body>
    </html>
  )
}
